if (LIBDW_FOUND)
    add_definitions(-DBACKWARD_HAS_DW=1)
    set(backward_ros_forced_LIBRARIES ${backward_ros_LIBRARIES} ${LIBDW_LIBRARIES})
elseif(LIBBFD_FOUND)
    add_definitions(-DBACKWARD_HAS_BFD=1)
    set(backward_ros_forced_LIBRARIES ${backward_ros_LIBRARIES} ${LIBBFD_LIBRARIES})
else()
    set(backward_ros_forced_LIBRARIES ${backward_ros_LIBRARIES})
endif()
if (ROSCPP_FOUND)
    add_definitions(-DBACKWARD_HAS_ROSCPP=1)
endif()
set(backward_ros_LIBRARIES "") #This is used by catkin, but we don't need it since we force it below
message("backward_ros_forced_LIBRARIES: ${backward_ros_forced_LIBRARIES} !!!")
message("backward_ros_DEVEL_PREFIX: ${backward_ros_DEVEL_PREFIX} !!!")
foreach(lib ${backward_ros_forced_LIBRARIES})
  message("${lib} tested !!!")
  if(NOT EXISTS ${lib})
    message("${lib} doesn't exist, trying to find it ???")
    find_file(path_to_lib 
      NAMES "lib${lib}.so" 
      PATHS ${backward_ros_PREFIX}
      PATH_SUFFIXES ${backward_ros_DEVEL_PREFIX} ${backward_ros_INSTALL_PREFIX})
    message("XXXXXXXXXXXXXXX ${path_to_lib} found")
    if(NOT ${path_to_lib})
      message("${lib} not found")
    else()
      message("${lib} found in ${path_to_lib}")
      list(APPEND backward_ros_LIBRARIES ${path_to_lib})
    endif()
  else()
    list(APPEND backward_ros_LIBRARIES ${lib})
  endif()
endforeach()
SET(CMAKE_EXE_LINKER_FLAGS "-Wl,--no-as-needed ${backward_ros_LIBRARIES} -Wl,--as-needed ${CMAKE_EXE_LINKER_FLAGS}")

